EMPTY_STRING = ''
UNSUPPORTED_PYTHON_VERSION_EXCEPTION_TEMPLATE = 'Unsupported Python Version: %s'

PYTHON27_VERSION = '2.7'
PYTHON28_VERSION = '2.8'
PYTHON34_VERSION = '3.4'
PYTHON35_VERSION = '3.5'
PYTHON37_VERSION = '3.7'
